services:
  app:
    image: 'lepresidente/nginxproxymanager:latest'
    container_name: npm
    restart: unless-stopped
    networks:
      npm:
    ports:
      - '80:80'  # Public HTTP Port
      - '443:443'  # Public HTTPS Port
      - '81:81'  # Admin Web Port
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_MYSQL_NAME: "npm"
      CROWDSEC_OPENRESTY_BOUNCER: |
        ENABLED=true
        API_URL=http://10.0.11.5:8080
        API_KEY=${CROWDSEC_BOUNCER_APIKEY}
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      wireguard:
        condition: service_healthy
      db:
        condition: service_healthy
    security_opt:
      - no-new-privileges=true

  db:
    image: 'mariadb:lts'
    container_name: db
    restart: unless-stopped
    networks:
      npm:
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    security_opt:
      - no-new-privileges=true
    healthcheck:
      test: [ 'CMD', '/usr/local/bin/healthcheck.sh', '--innodb_initialized' ]
      start_period: 5s
      timeout: 5s
      interval: 5s
      retries: 5

  wireguard:
    image: linuxserver/wireguard
    container_name: wg
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SERVERURL=${WG_HOST}
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=1.1.1.1,8.8.8.8
      - INTERNAL_SUBNET=10.8.0.0/24
      - ALLOWEDIPS=10.0.11.0/24
    volumes:
      - ./wg-config:/config:z
      - /lib/modules:/lib/modules:ro
    healthcheck:
      test: [ "CMD", "wg", "show", "wg0" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    network_mode: host
    dns:
      - 1.1.1.1
      - 8.8.8.8
#    sysctls:
#      - net.ipv4.conf.all.src_valid_mark=1
#      - net.ipv4.conf.all.forwarding=1
#      - net.ipv6.conf.all.forwarding=1
#      - net.ipv4.ip_forward=1
    restart: unless-stopped

volumes:
  mariadb-data:

networks:
  npm: