version: '3'

services:
  app:
    image: 'lepresidente/nginxproxymanager:latest'
    restart: unless-stopped
    networks:
      crowdsec:
      npm:
      wg-easy:
    ports:
      - '80:80'  # Public HTTP Port
      - '443:443'  # Public HTTPS Port
      - '81:81'  # Admin Web Port
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      DB_MYSQL_NAME: "npm"
      CROWDSEC_OPENRESTY_BOUNCER: |
        ENABLED=true
        API_URL=http://crowdsec:8080
        API_KEY=${CROWDSEC_BOUNCER_APIKEY}
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      db:
        condition: service_healthy
    security_opt:
      - no-new-privileges=true

  db:
    image: 'mariadb:lts'
    restart: unless-stopped
    networks:
      npm:
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_DATABASE_PASSWORD}
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    security_opt:
      - no-new-privileges=true
    healthcheck:
      test: [ 'CMD', '/usr/local/bin/healthcheck.sh', '--innodb_initialized' ]
      start_period: 5s
      timeout: 5s
      interval: 5s
      retries: 5

  crowdsec:
    image: docker.io/crowdsecurity/crowdsec:latest
    container_name: crowdsec
    environment:
      COLLECTIONS: 'crowdsecurity/nginx-proxy-manager'
      ENROLLMENT_KEY: ${CROWDSEC_ENROLLMENT_KEY}
    volumes:
      - crowdsec-db:/var/lib/crowdsec/data/
      - crowdsec-config:/etc/crowdsec/
      - ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ./data/logs/:/var/log/npm:ro
    networks:
      crowdsec:
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      WG_HOST: ${WG_HOST}
      PASSWORD: ${EASY_WG_PASSWORD}
      WG_PORT: 51820
      WG_PERSISTENT_KEEPALIVE: 25
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    volumes:
      - ./wg-easy:/etc/wireguard
    restart: unless-stopped
    networks:
      wg-easy:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1=1
      - net.ipv4.ip_forward=1

volumes:
  crowdsec-db:
  crowdsec-config:
  mariadb-data:

networks:
  crowdsec:
    driver: bridge
  npm:
    driver: bridge
  wg-easy:
    driver: bridge
